### ISSUE TITLE
Adding Torgan Mini Parse

### ISSUE THREAD

**Issue by MesTheGod** [ezsoftware/OverlayPlugin-Compiler#1]
Would it be possible to get Torgan Mini Parse Overlay added to your build?

Here is a link: http://angered.guildwork.com/forum/threads/559a80da002aa80f388a92dc-torgan-mini-parse-overlay

**Comment by ezsoftware** [comment]
I've added this to my fork of Billyvg's theme repo.  I've updated the existing release, so downloading a new update or running the installer with an update will incorporate the new themes.
