### ISSUE TITLE
Windows 10 - .Net Framework Error - CAS Policy

### ISSUE THREAD

**Issue by pkminer30** [ezsoftware/OverlayPlugin-Compiler#3]
Here is a printscreen of the error im getting. 

Latest ACT is installed
Latest FFXIV is installed
Using Version - OverlayPlugin.Full.Standard.0.3.3.9.EZS.Enmity-1.6.7.1.x64.zip
.Net Framework Version: 4.6.01038
(latest .net framework from recent windows 10 force update)

**Comment by pkminer30** [comment]
I found the fix - ACT config line after runtime added:  <loadFromRemoteSources enabled="true"/>

Seems to have fixed it + running act as Admin also helped :D

**Comment by EmperorArthur** [comment]
My initial search turned up this gem.  https://github.com/RainbowMage/OverlayPlugin/issues/24

It seems going into the properties of each dll and removing the untrusted tag worked, but I had to restart ACT first.

**Comment by veltall** [comment]
Don't forget to `Unblock` the Overlay zip **prior to extracting**.
